@port = 5000
@Host =  http://localhost

@route = api/v1/users

###

POST {{Host}}:{{port}}/{{route}}/register
Content-Type: application/json

{
    "username":"jun",
    "email":"jun@jun.com",
    "password":"12341234"
}

    # "email":"nena@nena.com",

###
POST {{Host}}:{{port}}/{{route}}/login
Content-Type: application/json

{
    "email":"jun@jun.com",
    "password":"12341234"
}

