@port = 5000
@Host =  http://localhost

@route = api/v1/movies

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTZmOGI1M2MyMzdmMWEzOTlhYjQ3MiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMzA4OTczNCwiZXhwIjoxNjMzNTIxNzM0fQ.jo-hp8D_D-uLX5R0yvBf3nU0zpyBJsZApVmBND04KzA

@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDA1YzRmZDlkNDY3YWEzNjc3YjU3OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzE2MDc4OTYsImV4cCI6MTYzMjAzOTg5Nn0.IJHCp8MaZvarvEgnNNir3Lp-PVQiKjOy7gq2-PmX744

@testMovieId = 614079bda906f1be48060794

@testSeriesId = 61407d77723bd7dbb0bff1fe
POST  {{Host}}:{{port}}/{{route}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "title":"friends",
    "isSeries":true
}


###

PUT  {{Host}}:{{port}}/{{route}}/{{testMovieId}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "title":"friends",
    "isSeries":true
}

###

DELETE {{Host}}:{{port}}/{{route}}/{{testMovieId}}
Authorization: Bearer {{adminToken}}

###

get {{Host}}:{{port}}/{{route}}/{{testMovieId}}
Authorization: Bearer {{adminToken}}


###

get {{Host}}:{{port}}/{{route}}/
Authorization: Bearer {{adminToken}}
